[tool.poetry]
name = "sekoiaio-documentation"
description = "An MkDocs server for SEKOIA.IO public Markdown documentation"
version = "1.0"
authors = []
packages = [
    { include = "plugins" }
]

[tool.poetry.plugins."mkdocs.plugins"]
redoc = "plugins.redoc:RedocPlugin"
intakes_by_uuid = "plugins.intakes_by_uuid:IntakesByUUIDPlugin"

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.4.3"
mkdocs-material = "^9.0.1"
mkdocs-redirects = "^1.2.0"
markdown-include = "^0.8.1"
lightgallery = "^0.5"

[tool.poetry.group.dev.dependencies]
mkdocs-material = "^9.1.1"

[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"
